### ISSUE TITLE
Repeated crashes

### ISSUE THREAD

**Issue by connorhsm** [twohoursonelife/junior#22]
Junior crashed twice in the last week.
No error first time, this time error was:
```
Ready! Logged in as Junior-C#2826
DiscordAPIError[10062]: Unknown interaction
    at SequentialHandler.runRequest (/app/node_modules/@discordjs/rest/dist/index.js:659:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.runRequest (/app/node_modules/@discordjs/rest/dist/index.js:528:16)
    at async SequentialHandler.queueRequest (/app/node_modules/@discordjs/rest/dist/index.js:458:14)
    at async REST.request (/app/node_modules/@discordjs/rest/dist/index.js:902:22)
    at async ChatInputCommandInteraction.reply (/app/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:111:5)
    at async Client.<anonymous> (/app/junior.js:35:3) {
  requestBody: { files: [], json: { type: 4, data: [Object] } },
  rawError: { message: 'Unknown interaction', code: 10062 },
  code: 10062,
  status: 404,
  method: 'POST',
  url: 'https://discord.com/api/v10/interactions/1044360494779211886/aW50ZXJhY3Rpb246MTA0NDM2MDQ5NDc3OTIxMTg4NjpHTGV5dVVFMUVxUndObU04NDdMQ0I3dFF1aXVNeUhxa3prWXlGZEh2TjhaaE1MemU0Y1JJVFk3MWtUR05mbWphWTdmWnRKbUN2dFozdU5mcmZZWnJXMTdkM2sxem5PeWhxM2hlc1I2bmVvbjNBbVNCZ1NENVlXVGJUVUwxWTAxaA/callback'
}
node:events:505
      throw er; // Unhandled 'error' event
      ^

DiscordAPIError[10062]: Unknown interaction
    at SequentialHandler.runRequest (/app/node_modules/@discordjs/rest/dist/index.js:659:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.queueRequest (/app/node_modules/@discordjs/rest/dist/index.js:458:14)
    at async REST.request (/app/node_modules/@discordjs/rest/dist/index.js:902:22)
    at async ChatInputCommandInteraction.reply (/app/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:111:5)
Emitted 'error' event on Client instance at:
    at emitUnhandledRejectionOrErr (node:events:384:10)
    at processTicksAndRejections (node:internal/process/task_queues:85:21) {
  requestBody: {
    files: [],
    json: {
      type: 4,
      data: {
        content: 'There was an error while executing this command!',
        tts: false,
        nonce: undefined,
        embeds: undefined,
        components: undefined,
        username: undefined,
        avatar_url: undefined,
        allowed_mentions: undefined,
        flags: 64,
        message_reference: undefined,
        attachments: undefined,
        sticker_ids: undefined,
        thread_name: undefined
      }
    }
  },
  rawError: { message: 'Unknown interaction', code: 10062 },
  code: 10062,
  status: 404,
  method: 'POST',
  url: 'https://discord.com/api/v10/interactions/1044360494779211886/aW50ZXJhY3Rpb246MTA0NDM2MDQ5NDc3OTIxMTg4NjpHTGV5dVVFMUVxUndObU04NDdMQ0I3dFF1aXVNeUhxa3prWXlGZEh2TjhaaE1MemU0Y1JJVFk3MWtUR05mbWphWTdmWnRKbUN2dFozdU5mcmZZWnJXMTdkM2sxem5PeWhxM2hlc1I2bmVvbjNBbVNCZ1NENVlXVGJUVUwxWTAxaA/callback'
}
```

I think Junior may be running Node.js 12, should probably update that and ensure discord.js is the latest version too.

**Comment by connorhsm** [comment]
Was running Node 16, not 12 as I thought. discord.js was only one minor version behind, so not sure of the issue.
Updating Node to 18 and all dependencies.
